# Generated by Django 3.1.1 on 2022-01-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='itens'),
        ),
    ]
