# Generated by Django 3.1.1 on 2022-02-15 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemcolecao',
            name='usuario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to='usuarios.customusuario'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='itemcolecao',
            name='disponivel_venda',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
