# Generated by Django 4.0.3 on 2022-12-12 02:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0003_alter_colecao_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('itens', '0003_alter_item_id_alter_itemcolecao_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='nome',
            new_name='nome_item',
        ),
        migrations.AddField(
            model_name='item',
            name='colecao',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='colecoes', to='colecoes.colecao'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='data_compra',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='disponivel_venda',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='estado_item',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='usuario',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='usuarios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='valor_pago',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='valor_venda',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.DeleteModel(
            name='ItemColecao',
        ),
    ]
