# Generated by Django 4.0.3 on 2022-03-21 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0002_colecao_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
