# Generated by Django 4.0 on 2022-01-13 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_id'),
        ('colecoes', '0002_auto_20211219_2203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colecao',
            name='item_usuario',
        ),
        migrations.AddField(
            model_name='colecao',
            name='data_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='colecao',
            name='usuario',
            field=models.ForeignKey(default=148, on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='usuarios.usuario'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colecao',
            name='valor_estimado',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
