# Generated by Django 3.1.1 on 2022-01-20 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colecoes', '0002_auto_20220118_2254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colecao',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='colecoes'),
        ),
    ]
