# Generated by Django 4.0.3 on 2022-12-11 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='cpf',
            field=models.CharField(blank=True, error_messages={'unique': 'CPF já cadastrado'}, max_length=14, null=True),
        ),
        migrations.AlterField(
            model_name='customusuario',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
