# Generated by Django 3.1.1 on 2022-01-28 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusuario',
            name='last_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
